- name: Install base packages
  ansible.builtin.apt:
    name:
      - curl
      - python3-pip
      - sudo
      - vim
    update_cache: yes
    cache_valid_time: 86400  # 24H

- name: Set timezone to Europe/Berlin
  community.general.timezone:
    name: Europe/Berlin
