name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        description: The environment to be deployed (prod/staging)
        type: string
    secrets:
      SERVER_IP:
        required: true
        description: The IP address or domain of the server (can include port)
      SERVER_SIGNATURE:
        required: true
        description: The signature of the server (use ssh-keyscan to generate it)
      SSH_DEPLOY_USER:
        required: true
        description: The user used for deploying (probably `deploy`)
      SSH_DEPLOY_KEY:
        required: true
        description: The private ssh key used to connect to the server

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - shell: bash
        run: |
            echo "Deploying to ${{ secrets.SERVER_IP }}"
            eval $(ssh-agent -s)
            echo "${{ secrets.SSH_DEPLOY_KEY }}" | tr -d '\r' | ssh-add -
            mkdir -p -m 700 ~/.ssh
            echo "${{ secrets.SERVER_SIGNATURE }}" >> ~/.ssh/known_hosts
            chmod 644 ~/.ssh/known_hosts
            ssh -t {{ secrets.SSH_DEPLOY_USER }}@${{ secrets.SERVER_IP }}
